# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clive',
            new_name='Post',
        ),
    ]
